### ISSUE TITLE
naming mismatch: HandlerOpts vs NewServer / Server

### ISSUE THREAD

**Issue by bgentry** [riverqueue/riverui#130]
The standalone `Handler` type was renamed to `Server` as part of some refactoring in #108, as was the `NewHandler` constructor (now `NewServer`). However, the `HandlerOpts` type was not renamed. Prior to shipping the next release with a functional embeddable `http.Handler` interface, we should probably align these API names.

Agree @brandur? Do you think `HandlerOpts` should just become `ServerOpts`?

**Comment by brandur** [comment]
Yeah, should be `ServerOpts`.
