### ISSUE TITLE
exported top-level DBTXWithBegin type references internal dbsqlc package

### ISSUE THREAD

**Issue by bgentry** [riverqueue/riverui#131]
The `DBTXWithBegin` type is needed to use the embeddable `http.Handler` setup, but it embeds a type from an internal package which seems like a weird API design choice. Go doc actually [does handle it well](https://pkg.go.dev/riverqueue.com/riverui@v0.5.0-pre3#DBTXWithBegin) surprisingly, but I wonder if we may want to tweak this to fully specify the interface inline? 

cc @brandur

**Comment by brandur** [comment]
Yeah should be fine to specify it inline. Sqlc's interface has been quite stable over time, and the compiler will tell us the second anything breaks, should it break.
