### ISSUE TITLE
snoozed jobs break the ui

### ISSUE THREAD

**Issue by dzfranklin** [riverqueue/riverui#136]
If I click on a snoozed job I see the error `e.errors[(e.errors.length - 1)] is undefined`. They also show up with a red dot as though they failed.

<img width="424" alt="Screenshot 2024-08-30 at 3 20 40 PM" src="https://github.com/user-attachments/assets/bcfabf5f-07eb-429d-bcbc-3d4c189c096b">
<img width="414" alt="Screenshot 2024-08-30 at 3 21 45 PM" src="https://github.com/user-attachments/assets/91742942-0c66-4581-ac9e-d4d3308b8c0d">

**Comment by bgentry** [comment]
Can you snag the job’s json payload from the inspector and share here (redacting any args or other stuff you consider sensitive)? Should be an easy fix.

**Comment by dzfranklin** [comment]
apologies for wasting your time, I was running an outdated version

**Comment by bgentry** [comment]
Good to know, I thought I had just fixed all the issues with this 😅
