### ISSUE TITLE
Live Update / Colour Scheme buttons don't seem to work

### ISSUE THREAD

**Issue by arp242** [riverqueue/riverui#138]
The buttons at the top don't seem to do anything? It opens, I select something, but nothing changes, and when I open it again the old value is still selected.

Tested in Firefox and Chromium.

Version baaa2e5

https://github.com/user-attachments/assets/f57d72a9-383d-4590-86fc-8b0ae7684d67

**Comment by bgentry** [comment]
Must have regressed in a dependency upgrade, sorting that out now. Thanks for the report!

**Comment by bgentry** [comment]
@arp242 can you confirm how you're using this? Interestingly I'm getting this on ui.riverqueue.com, but not when I try to reproduce locally (even with built assets). Thinking it might be something specific to the embedded handler somehow.

**Comment by arp242** [comment]
I first noticed when running from the Docker container, bb9f755ef45e.

I also ran it directly (`npm install`, `go build`, `DATABASE_URL=.. ./riverui`) because I wanted to look at fixing it as it seemed a simple problem, but all this React stuff confused me so I gave up on that.

I just tried running with `LIVE_FS=y`, `DEV=y`, and `LIVE_FS=y DEV=y`, and that doesn't seem to make a difference.

**Comment by bgentry** [comment]
Fix is coming in #139 / v0.5.1 shortly, thanks again for finding + reporting 🙏
