### ISSUE TITLE
Docker pull gives an access denied error

### ISSUE THREAD

**Issue by advdv** [riverqueue/riverui#182]
I might be doing something stupid, or maybe it's a temporary error but currently when i run: `docker pull ghcr.io/riverqueue/riverui:latest`, I get:

```
Error response from daemon: Head "https://ghcr.io/v2/riverqueue/riverui/manifests/latest": denied: denied
```

**Comment by bgentry** [comment]
Same, works fine here. Not sure if it’s somehow related to me being authenticated, but I will need more info to be able to debug this one.

Closing for now but will happily reopen if we can find a way to reproduce this.

**Comment by advdv** [comment]
Right i figured it was something on my side, for anyone else coming here. I had expired credentials for ghcr that it was using (not sure why?). This solved it for me: https://stackoverflow.com/questions/74656167/unable-to-pull-image-from-github-container-registry-ghcr
