### ISSUE TITLE
The live demo returns a 500 for the jobs page

### ISSUE THREAD

**Issue by rhodeon** [riverqueue/riverui#193]
Not sure if this is better suited as an issue or a discussion, but https://ui.riverqueue.com/jobs currently displays an error page.
Both the queues and workflow pages work fine.
![image](https://github.com/user-attachments/assets/4b8613a2-9adb-45db-89bb-13723f574316)

**Comment by bgentry** [comment]
Ugh, I botched the upgrade / migration on a prerelease version and still haven't set up exception tracking on the demo app. Thank you, fixed now!
