### ISSUE TITLE
how do i pull image with specific version?

### ISSUE THREAD

**Issue by rizalalfarizi123** [riverqueue/riverui#194]
hello, i want to use riverui v0.5.3, but since you are using tag based on somehing hash (e.g [sha256-22ce64a148758b0965e126c8ee4b1980028d9b1dc4e481a5f88dbd3dd0bcf820](https://github.com/orgs/riverqueue/packages/container/riverui/278285414?tag=sha256-22ce64a148758b0965e126c8ee4b1980028d9b1dc4e481a5f88dbd3dd0bcf820), can you provide example how to do that?

**Comment by bgentry** [comment]
https://github.com/riverqueue/riverui/discussions/185#discussioncomment-10725928
