### ISSUE TITLE
Frontend Undefined Variable

### ISSUE THREAD

**Issue by Zibbp** [riverqueue/riverui#60]
Attempting to browse the WebUI results in the API requests returning a status of 404. Looks like this is because a variable in the frontend is undefined.
```
http://localhost:8080/undefined/jobs?state=running&limit=20
```
I'm guessing this is the undefined part.
https://github.com/riverqueue/riverui/blob/698220a7e18ed3de3666b41633740f9fa6770812/ui/src/utils/api.ts#L24-L28

Vite env vars are statically replaced at build time. I don't see a real `.env` in the UI directory, resulting in the variable being undefined.

The backend/API is correctly functioning.
```bash
$ curl localhost:8080/api/states
{"available":0,"cancelled":0,"completed":66,"discarded":90,"pending":0,"retryable":0,"running":0,"scheduled":0}
```

Unless I'm missing a design choice, removing the env variable and hardcoding `/api` should be fine as they're hosted on the same service/port. Not sure if the below will work being a 'partial' URL but the idea is:
```javascript
 export function APIUrl(path: string, query?: URLSearchParams) { 
   return `/api${path}${ 
     query ? `?${query}` : "" 
   }`; 
 } 
```

**Comment by bgentry** [comment]
Hi @Zibbp, sorry you're running into this. Can you confirm if you're using the prebuilt docker image, or something else?

**Comment by bgentry** [comment]
@Zibbp I'm seeing this issue in the prebuilt binaries, while the Docker images appear to be fine.

**Comment by Zibbp** [comment]
Sorry, forgot to mention. I'm using the prebuilt binaries. I'll try out the Docker image now.

**Comment by Zibbp** [comment]
Thank you for the quick fix!
