### ISSUE TITLE
Handle no-permissions error from postgres

### ISSUE THREAD

**Issue by isaacd9** [riverqueue/riverui#73]
Because `riverui` is unauthenticated right now and has no permissions checks for users, I've opted to use it with a read-only Postgres user in our deployment to avoid accidentally cancelling or restarting running jobs. This user can read the state of all jobs, but cannot modify any.

This works fine to display jobs, but any modifying action returns a 500 right now. It would be better if riverui could return a more descriptive error in that case.

**Comment by brandur** [comment]
Yeah, that's a good idea.

**Comment by bgentry** [comment]
@brandur I think this was resolved by #76?

**Comment by brandur** [comment]
Yep, in conjunction with #77 and #78 which converted the remaining API endpoints over to the framework that handles the error.
